ansible_user: "{{ user }}"
ansible_host: "{{ user }}.sakura.ne.jp"
ansible_ssh_private_key_file: "~/.ssh/{{ user }}"
ansible_python_interpreter: "/usr/local/bin/python"

# host として変数を含んだホスト名を指定しているので、
# playbook 側で prompt_vars などで変数部分の入力を促す。
# playbook を指定しないで実行する場合、-e オプションで変数部分を指定する。
# 例：ansible -m setup -e user=XXX sakura-rental-server